# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `cypress-on-rails` gem.
# Please instead update this file by running `bin/tapioca gem cypress-on-rails`.


# source://cypress-on-rails//lib/cypress-on-rails.rb#7
Cypress = CypressOnRails

# maintain backward compatibility
#
# source://cypress-on-rails//lib/cypress-on-rails.rb#6
CypressDev = CypressOnRails

# source://cypress-on-rails//lib/cypress_on_rails/version.rb#1
module CypressOnRails
  class << self
    # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#47
    def configuration; end

    # @yield [configuration]
    #
    # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#51
    def configure; end
  end
end

# source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#4
class CypressOnRails::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#22
  def initialize; end

  # Returns the value of attribute api_prefix.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#5
  def api_prefix; end

  # Sets the attribute api_prefix
  #
  # @param value the value to set the attribute api_prefix to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#5
  def api_prefix=(_arg0); end

  # Returns the value of attribute before_request.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#9
  def before_request; end

  # Sets the attribute before_request
  #
  # @param value the value to set the attribute before_request to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#9
  def before_request=(_arg0); end

  # Attributes for backwards compatibility
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#13
  def cypress_folder; end

  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#17
  def cypress_folder=(v); end

  # Returns the value of attribute install_folder.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#6
  def install_folder; end

  # Sets the attribute install_folder
  #
  # @param value the value to set the attribute install_folder to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#6
  def install_folder=(_arg0); end

  # Returns the value of attribute logger.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#10
  def logger; end

  # Sets the attribute logger
  #
  # @param value the value to set the attribute logger to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#10
  def logger=(_arg0); end

  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#29
  def reset; end

  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#38
  def tagged_logged; end

  # Returns the value of attribute use_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#7
  def use_middleware; end

  # Sets the attribute use_middleware
  #
  # @param value the value to set the attribute use_middleware to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#7
  def use_middleware=(_arg0); end

  # Returns the value of attribute use_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#7
  def use_middleware?; end

  # Returns the value of attribute use_vcr_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#8
  def use_vcr_middleware; end

  # Sets the attribute use_vcr_middleware
  #
  # @param value the value to set the attribute use_vcr_middleware to.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#8
  def use_vcr_middleware=(_arg0); end

  # Returns the value of attribute use_vcr_middleware.
  #
  # source://cypress-on-rails//lib/cypress_on_rails/configuration.rb#8
  def use_vcr_middleware?; end
end

# source://cypress-on-rails//lib/cypress_on_rails/railtie.rb#5
class CypressOnRails::Railtie < ::Rails::Railtie; end

# source://cypress-on-rails//lib/cypress_on_rails/version.rb#2
CypressOnRails::VERSION = T.let(T.unsafe(nil), String)
