# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sofia` gem.
# Please instead update this file by running `bin/tapioca gem sofia`.


# source://sofia//lib/sofia/version.rb#3
module Sofia
  class << self
    # : (base_url: untyped, ?adapter: untyped) -> Sofia::Client
    #
    # source://sofia//lib/sofia.rb#21
    def new(base_url:, adapter: T.unsafe(nil)); end
  end
end

# source://sofia//lib/sofia/adapter.rb#5
module Sofia::Adapter; end

# @abstract
#
# source://sofia//lib/sofia/adapter.rb#7
class Sofia::Adapter::Base
  abstract!

  class << self
    # @abstract
    #
    # source://sofia//lib/sofia/adapter.rb#14
    sig { abstract.params(request: ::Sofia::Request).returns(::Sofia::Response) }
    def call(request); end
  end
end

# source://sofia//lib/sofia/adapter/net_http.rb#6
class Sofia::Adapter::NetHTTP < ::Sofia::Adapter::Base
  class << self
    # : (Sofia::Request request) -> Sofia::Response
    #
    # @raise [Sofia::Error::ArgumentError]
    #
    # source://sofia//lib/sofia/adapter/net_http.rb#19
    def call(request); end

    private

    # : (Net::HTTPResponse response, Sofia::Request request) -> Sofia::Response
    #
    # source://sofia//lib/sofia/adapter/net_http.rb#44
    def adapt_response(response, request); end

    # : (Net::HTTP http, Net::HTTPRequest net_req) -> Net::HTTPResponse
    #
    # source://sofia//lib/sofia/adapter/net_http.rb#54
    def perform_request(http, net_req); end
  end
end

# source://sofia//lib/sofia/client.rb#5
class Sofia::Client
  # : (base_url: untyped, adapter: untyped) -> void
  #
  # @return [Client] a new instance of Client
  #
  # source://sofia//lib/sofia/client.rb#9
  def initialize(base_url:, adapter:); end

  # : -> Symbol
  #
  # source://sofia//lib/sofia/client.rb#20
  def adapter; end

  # : -> String
  #
  # source://sofia//lib/sofia/client.rb#15
  def base_url; end

  # : ?{ (Request req) -> untyped } -> Response
  #
  # source://sofia//lib/sofia/client.rb#37
  def delete(&_arg0); end

  # : ?{ (Request req) -> untyped } -> Response
  #
  # source://sofia//lib/sofia/client.rb#25
  def get(&_arg0); end

  # : ?{ (Request req) -> untyped } -> Response
  #
  # source://sofia//lib/sofia/client.rb#34
  def patch(&_arg0); end

  # : ?{ (Request req) -> untyped } -> Response
  #
  # source://sofia//lib/sofia/client.rb#28
  def post(&_arg0); end

  # : ?{ (Request req) -> untyped } -> Response
  #
  # source://sofia//lib/sofia/client.rb#31
  def put(&_arg0); end

  private

  # : (Symbol http_method) ?{ ( Request req ) -> untyped } -> Response
  #
  # @raise [Sofia::Error::ArgumentError]
  #
  # source://sofia//lib/sofia/client.rb#42
  def request(http_method, &block); end
end

# source://sofia//lib/sofia/client.rb#6
Sofia::Client::HTTP_METHODS = T.let(T.unsafe(nil), Array)

# source://sofia//lib/sofia/error.rb#5
module Sofia::Error; end

# source://sofia//lib/sofia/error/argument_error.rb#6
class Sofia::Error::ArgumentError < ::Sofia::Error::Base; end

# source://sofia//lib/sofia/error.rb#6
class Sofia::Error::Base < ::StandardError; end

# source://sofia//lib/sofia/error/connection_failed.rb#6
class Sofia::Error::ConnectionFailed < ::Sofia::Error::Base; end

# source://sofia//lib/sofia/error/parser_error.rb#6
class Sofia::Error::ParserError < ::Sofia::Error::Base; end

# source://sofia//lib/sofia/error/ssl_error.rb#6
class Sofia::Error::SSLError < ::Sofia::Error::Base; end

# source://sofia//lib/sofia/error/timeout_error.rb#6
class Sofia::Error::TimeoutError < ::Sofia::Error::Base; end

# source://sofia//lib/sofia/request.rb#5
class Sofia::Request
  # : (http_method: Symbol, base_url: Sofia::Types::BaseUrl) -> void
  #
  # @return [Request] a new instance of Request
  #
  # source://sofia//lib/sofia/request.rb#20
  def initialize(http_method:, base_url:); end

  # : Sofia::Types::Body
  #
  # source://sofia//lib/sofia/request.rb#17
  def body; end

  # : (untyped? body) -> void
  #
  # source://sofia//lib/sofia/request.rb#45
  def body=(body); end

  # : Sofia::Types::Headers
  #
  # source://sofia//lib/sofia/request.rb#11
  def headers; end

  # : (untyped headers) -> void
  #
  # source://sofia//lib/sofia/request.rb#40
  def headers=(headers); end

  # : Symbol
  #
  # source://sofia//lib/sofia/request.rb#8
  def http_method; end

  # : Sofia::Types::Params
  #
  # source://sofia//lib/sofia/request.rb#14
  def params; end

  # : (untyped params) -> void
  #
  # source://sofia//lib/sofia/request.rb#35
  def params=(params); end

  # : (untyped path) -> void
  #
  # source://sofia//lib/sofia/request.rb#30
  def path=(path); end

  # : -> String
  #
  # source://sofia//lib/sofia/request.rb#50
  def url; end
end

# source://sofia//lib/sofia/response.rb#5
class Sofia::Response
  # : (status: Integer, headers: Hash[String, String], raw_body: String?, request: Sofia::Request) -> void
  #
  # @return [Response] a new instance of Response
  #
  # source://sofia//lib/sofia/response.rb#20
  def initialize(status:, headers:, raw_body:, request:); end

  # : -> JSONValue?
  #
  # source://sofia//lib/sofia/response.rb#38
  def body; end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://sofia//lib/sofia/response.rb#48
  def client_error?; end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://sofia//lib/sofia/response.rb#33
  def failure?; end

  # : Hash[String, String]
  #
  # source://sofia//lib/sofia/response.rb#11
  def headers; end

  # : String?
  #
  # source://sofia//lib/sofia/response.rb#14
  def raw_body; end

  # : Sofia::Request
  #
  # source://sofia//lib/sofia/response.rb#17
  def request; end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://sofia//lib/sofia/response.rb#53
  def server_error?; end

  # : Integer
  #
  # source://sofia//lib/sofia/response.rb#8
  def status; end

  # : -> bool
  #
  # @return [Boolean]
  #
  # source://sofia//lib/sofia/response.rb#28
  def success?; end
end

# source://sofia//lib/sofia/types.rb#5
module Sofia::Types; end

# source://sofia//lib/sofia/types/adapter.rb#6
class Sofia::Types::Adapter
  # : (?untyped adapter) -> void
  #
  # @return [Adapter] a new instance of Adapter
  #
  # source://sofia//lib/sofia/types/adapter.rb#12
  def initialize(adapter = T.unsafe(nil)); end

  # : singleton(Sofia::Adapter::Base)
  #
  # source://sofia//lib/sofia/types/adapter.rb#9
  def klass; end

  # : -> Symbol
  #
  # source://sofia//lib/sofia/types/adapter.rb#19
  def to_sym; end

  private

  # : (untyped) -> [Symbol, singleton(Sofia::Adapter::Base)]
  #
  # source://sofia//lib/sofia/types/adapter.rb#26
  def validate_and_set(adapter); end
end

# source://sofia//lib/sofia/types/base_url.rb#6
class Sofia::Types::BaseUrl
  # : (untyped base_url) -> void
  #
  # @return [BaseUrl] a new instance of BaseUrl
  #
  # source://sofia//lib/sofia/types/base_url.rb#9
  def initialize(base_url); end

  # : -> String
  #
  # source://sofia//lib/sofia/types/base_url.rb#14
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://sofia//lib/sofia/types/base_url.rb#21
  def validate_and_normalize(base_url); end
end

# source://sofia//lib/sofia/types/body.rb#6
class Sofia::Types::Body
  # : (?untyped? body) -> void
  #
  # @return [Body] a new instance of Body
  #
  # source://sofia//lib/sofia/types/body.rb#12
  def initialize(body = T.unsafe(nil)); end

  # :  Hash[String, untyped]
  #
  # source://sofia//lib/sofia/types/body.rb#9
  def body; end

  # : -> Hash[String, untyped]
  #
  # source://sofia//lib/sofia/types/body.rb#17
  def to_h; end

  private

  # : (untyped? body) -> Hash[String, untyped]
  #
  # source://sofia//lib/sofia/types/body.rb#24
  def validate_and_normalize(body); end

  # : (Array[untyped]) -> Array[untyped]
  #
  # source://sofia//lib/sofia/types/body.rb#44
  def validate_and_normalize_array(array); end
end

# source://sofia//lib/sofia/types/headers.rb#6
class Sofia::Types::Headers
  # : (?untyped headers) -> void
  #
  # @return [Headers] a new instance of Headers
  #
  # source://sofia//lib/sofia/types/headers.rb#9
  def initialize(headers = T.unsafe(nil)); end

  # : (untyped key) -> void
  #
  # source://sofia//lib/sofia/types/headers.rb#16
  def [](key); end

  # : (untyped key, untyped value) -> void
  #
  # source://sofia//lib/sofia/types/headers.rb#21
  def []=(key, value); end

  # : () { ([String, String]) -> untyped } -> Hash[String, String]
  #
  # source://sofia//lib/sofia/types/headers.rb#31
  def each(&block); end

  # : -> Hash[String, String]
  #
  # source://sofia//lib/sofia/types/headers.rb#26
  def to_h; end

  private

  # : (untyped) -> Hash[String, String]
  #
  # source://sofia//lib/sofia/types/headers.rb#38
  def validate_and_normalize(headers); end
end

# source://sofia//lib/sofia/types/params.rb#6
class Sofia::Types::Params
  # : (?untyped params) -> void
  #
  # @return [Params] a new instance of Params
  #
  # source://sofia//lib/sofia/types/params.rb#11
  def initialize(params = T.unsafe(nil)); end

  # : (untyped key) -> void
  #
  # source://sofia//lib/sofia/types/params.rb#16
  def [](key); end

  # : (untyped key, untyped value) -> void
  #
  # source://sofia//lib/sofia/types/params.rb#21
  def []=(key, value); end

  # : -> Hash[String, String]
  #
  # source://sofia//lib/sofia/types/params.rb#26
  def to_h; end

  # : -> String
  #
  # source://sofia//lib/sofia/types/params.rb#31
  def to_s; end

  private

  # : (untyped) -> Hash[String, String]
  #
  # source://sofia//lib/sofia/types/params.rb#38
  def validate_and_normalize(headers); end
end

# source://sofia//lib/sofia/types/path.rb#6
class Sofia::Types::Path
  # : (?untyped path) -> void
  #
  # @return [Path] a new instance of Path
  #
  # source://sofia//lib/sofia/types/path.rb#9
  def initialize(path = T.unsafe(nil)); end

  # : -> String
  #
  # source://sofia//lib/sofia/types/path.rb#14
  def to_s; end

  private

  # : (untyped) -> String
  #
  # source://sofia//lib/sofia/types/path.rb#21
  def validate_and_normalize(path); end
end

# source://sofia//lib/sofia/version.rb#4
Sofia::VERSION = T.let(T.unsafe(nil), String)
