// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoRenewToggleController from "./auto_renew_toggle_controller"
application.register("auto-renew-toggle", AutoRenewToggleController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaymentController from "./payment_controller"
application.register("payment", PaymentController)

import PrimarySavedPaymentMethodToggleController from "./primary_saved_payment_method_toggle_controller"
application.register("primary-saved-payment-method-toggle", PrimarySavedPaymentMethodToggleController)
