// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EspagoIframeController from "./espago_iframe_controller"
application.register("espago-iframe", EspagoIframeController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaymentMethodController from "./payment_method_controller"
application.register("payment-method", PaymentMethodController)
