# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ResignOrderJob`.
# Please instead update this file by running `bin/tapioca dsl ResignOrderJob`.


class ResignOrderJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: ResignOrderJob).void)
      ).returns(T.any(ResignOrderJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
