# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ResignPaymentJob`.
# Please instead update this file by running `bin/tapioca dsl ResignPaymentJob`.


class ResignPaymentJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: ResignPaymentJob).void)
      ).returns(T.any(ResignPaymentJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
