:scheduler:
  :schedule:
    expire_subscriptions:
      cron: "0 0 * * * *"
      class: ExpireSubscriptionJob
      queue: default
    finalize_payments_job:
      cron: "0 0 * * * *"
      class: FinalizePaymentJob
      queue: default